feat: refactored the workflow to speed it up

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -16,7 +16,31 @@ permissions:
     contents: "read" # to fetch code (actions/checkout)
 
 jobs:
+    files-changed:
+        name: "Detect what files changed"
+        runs-on: "ubuntu-20.04"
+        timeout-minutes: 3
+        # Map a step output to a job output
+        outputs:
+            frontend_lintable: "${{ steps.changes.outputs.frontend_lintable }}"
+            markdown_lintable: "${{ steps.changes.outputs.markdown_lintable }}"
+        steps:
+          - name: "Git checkout"
+            uses: "actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab" # v3.5.2
+            env:
+                GIT_COMMITTER_NAME: "GitHub Actions Shell"
+                GIT_AUTHOR_NAME: "GitHub Actions Shell"
+                EMAIL: "github-actions[bot]@users.noreply.github.com"
+
+          - name: "Check for backend file changes"
+            uses: "getsentry/paths-filter@66f7f1844185eb7fb6738ea4ea59d74bb99199e5"  # v2
+            id: "changes"
+            with:
+                token: "${{ github.token }}"
+                filters: ".github/file-filters.yml"
+
     eslint:
+        if: "needs.files-changed.outputs.frontend_lintable == 'true'"
         name: "Lint (eslint)"
 
         runs-on: "ubuntu-latest"
@@ -85,3 +109,63 @@ jobs:
                   config_file: ".yamllint.yaml"
                   file_or_dir: "."
                   strict: true
+
+    text-lint:
+        name: "Lint (markdown)"
+
+        runs-on: "ubuntu-latest"
+
+        steps:
+            - name: "Harden Runner"
+              uses: "step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969" # v2.4.0
+              with:
+                  egress-policy: "audit"
+
+            - name: "Git checkout"
+              uses: "actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab" # v3.5.2
+              with:
+                  fetch-depth: 2
+              env:
+                  GIT_COMMITTER_NAME: "GitHub Actions Shell"
+                  GIT_AUTHOR_NAME: "GitHub Actions Shell"
+                  EMAIL: "github-actions[bot]@users.noreply.github.com"
+
+            - uses: "pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd" # v2.2.4
+              with:
+                  version: 8
+                  run_install: false
+
+            - name: "Use Node.js 16.x"
+              uses: "actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c" # v3.6.0
+              with:
+                  node-version: "16.x"
+                  cache: "pnpm"
+
+            - name: "Install packages"
+              run: "pnpm install --frozen-lockfile"
+              env:
+                  SKIP_CHECK: "true"
+
+            - name: "Verify the integrity of provenance attestations and registry signatures for installed dependencies"
+              run: "npm audit signatures"
+
+            - name: "lint"
+              run: "pnpm run lint:text"
+
+
+    # This check runs once all dependant jobs have passed
+    # It symbolizes that all required Frontend checks have succesfully passed (Or skipped)
+    # This check is the only required Github check
+    test-required-check:
+        needs: ["Lint (eslint)", "Lint (yaml)"] # TODO add "Lint (markdown)"
+        name: "Check Lint Run"
+        # This is necessary since a failed/skipped dependent job would cause this job to be skipped
+        if: "always()"
+        runs-on: "ubuntu-20.04"
+        steps:
+            # If any jobs we depend on fail, we will fail since this is a required check
+            # NOTE: A timeout is considered a failure
+            - name: "Check for failures"
+              if: "contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')"
+              run: |
+                  echo "One of the dependent jobs have failed. You may need to re-run it." && exit 1
diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -16,7 +16,30 @@ permissions:
     contents: "read" # to fetch code (actions/checkout)
 
 jobs:
+    files-changed:
+        name: "Detect what files changed"
+        runs-on: "ubuntu-20.04"
+        timeout-minutes: 3
+        # Map a step output to a job output
+        outputs:
+            packages: "${{ steps.changes.outputs.packages }}"
+        steps:
+          - name: "Git checkout"
+            uses: "actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab" # v3.5.2
+            env:
+                GIT_COMMITTER_NAME: "GitHub Actions Shell"
+                GIT_AUTHOR_NAME: "GitHub Actions Shell"
+                EMAIL: "github-actions[bot]@users.noreply.github.com"
+
+          - name: "Check for backend file changes"
+            uses: "getsentry/paths-filter@66f7f1844185eb7fb6738ea4ea59d74bb99199e5"  # v2
+            id: "changes"
+            with:
+                token: "${{ github.token }}"
+                filters: ".github/file-filters.yml"
+
     test:
+        if: "needs.files-changed.outputs.packages == 'true'"
         strategy:
             matrix:
                 os: ["ubuntu-latest", "windows-latest", "macos-latest"]
@@ -69,3 +92,20 @@ jobs:
 
             - name: "test and coverage"
               run: "pnpm run test:coverage"
+
+    # This check runs once all dependant jobs have passed
+    # It symbolizes that all required Frontend checks have succesfully passed (Or skipped)
+    # This check is the only required Github check
+    test-required-check:
+        needs: ["files-changed", "test"]
+        name: "Check Test Run"
+        # This is necessary since a failed/skipped dependent job would cause this job to be skipped
+        if: "always()"
+        runs-on: "ubuntu-20.04"
+        steps:
+            # If any jobs we depend on fail, we will fail since this is a required check
+            # NOTE: A timeout is considered a failure
+            - name: "Check for failures"
+              if: "contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')"
+              run: |
+                  echo "One of the dependent jobs have failed. You may need to re-run it." && exit 1
